on:
  release:
    types: [released]

name: Deploy Released

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Hello im running in released"
