on:
  push:
    branches:
      - master

name: Deploy to staging

jobs:
  create-github-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version number
        id: version-number
        run: echo "::set-output name=version::$(git rev-parse --short=7 HEAD)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.version-number.outputs.version }}-staging
          release_name: ${{ steps.version-number.outputs.version }}-staging
          body: "This release refers to HEAD at ${{ steps.version-number.outputs.version }}"
          draft: false
          prerelease: true
